src/auth/oidc/index.ts
=> refactor(authroute): moved auth route to node lib & add it to options

src/auth/oidc/index.ts, src/auth/oidc/oidc.constants.ts
=> refactor(all auth routes): moving all Auth routes to constants now

src/auth/oidc/index.ts
=> refactor(logouturl): move idamAPI url as an option

lint-staged.config.js, src/auth/oidc/index.spec.ts, src/auth/oidc/index.ts, src/auth/oidc/oidc.constants.ts
=> fix(routes): fixed open/closed route issue

.github/workflows/semantic-release.yml, package.json, src/auth/oidc/index.ts, src/auth/oidc/validation/openIdOptions.validation.ts, yarn.lock
check to ensure each request gets a new set of tokens if there is a refresh_token available and
existing access_token has expired
```
[ ] Yes
[ ] No
```
=> fix(oidc): refresh token

.github/workflows/semantic-release.yml, release.config.js
=> feat(pipeline): add semantic release

README.md
=> fix(pipeline): test release

README.md
=> Semantic release test

src/auth/models/authOptions.interface.ts, src/auth/models/optionsMapper.class.spec.ts, src/auth/models/optionsMapper.class.ts
=> feature(authoption): generic Auth Options

.github/workflows/prbuild.yml
=> feat(pipeline): enable sonar on master

docs/test.md
=> fix(pipeline): test protected branch

docs/test.md
=> Test protected branch

__mocks__/jwt-decode.ts, docs/test.md, jest.config.js, src/auth/models/strategy.class.ts, src/auth/oidc/models/openid.class.spec.ts, src/auth/s2s/s2s.class.spec.ts, src/auth/s2s/s2s.class.ts
https://tools.hmcts.net/jira/browse/EUI-1970
Implement proper unit tests; refactor to use arrow functions as class properties due to `this` scoping.
```
[ ] Yes
[x] No
```
=> feat(s2s): add unit tests and refactor

config.ts, jest.config.js, package.json, src/examples/tsAutoMockExample.spec.ts, tsconfig.json, yarn.lock
Jest auto mock
@see https://medium.com/@vittorioguerriero/jest-with-ts-auto-mock-real-mocks-da9a181792dd
=> Jest Auto Mock.

src/auth/oidc/models/openid.class.spec.ts, src/auth/oidc/models/openid.class.ts, yarn.lock
=> test(auth): added authentication unit tests

src/auth/s2s/s2s.class.ts
=> refactor(s2s): fix the import

.github/workflows/prbuild.yml
=> feat(pipeline): add PR commit rules for master

.github/workflows/prbuild.yml
=> Enforce commit rule

.github/workflows/prbuild.yml
=> feat(pipeline): Enforce commit rule

.github/workflows/prbuild.yml
=> feat(pipeline): amend workflow steps

.github/workflows/prbuild.yml
=> feat(pipeline): amend steps

.github/workflows/prbuild.yml
=> fix(pipeline): fix steps

.github/workflows/prbuild.yml, .github/workflows/prlint.yml
=> fix(pipeline): separate pr title lint to another workflow

src/auth/messaging.constants.ts, src/auth/oidc/models/openid.class.spec.ts, src/auth/oidc/models/openid.class.ts
Adding more unit tests around openid.class.ts
=> test(fixing unit tests.): fixing unit tests

src/auth/oauth2/models/XUIOAuth2Strategy.class.spec.ts, src/auth/oauth2/models/XUIOAuth2Strategy.class.ts
=> test(xuioauth2strategy): adding unit tests

src/common/models/xuiNode.class.spec.ts, src/common/models/xuiNode.class.ts
Adding a unit test around xuiNode.class.ts
=> test: xuinodeclass unit test

.github/workflows/prbuild.yml
=> ci(pipeline): exit jobs early when previous job failed

.github/workflows/prbuild.yml
=> ci(pipeline): add slack integration

package.json, src/auth/oauth2/models/index.ts, src/auth/oauth2/models/oauth2.class.spec.ts, src/auth/oauth2/models/oauth2.class.ts, src/auth/oidc/models/index.ts, src/auth/oidc/models/openid.class.spec.ts, src/auth/oidc/models/openid.class.ts, src/auth/s2s/index.ts, src/auth/s2s/s2s.class.ts, src/common/models/index.ts, src/common/models/xuiNode.class.spec.ts, src/common/models/xuiNode.class.ts, src/session/models/fileSessionStore.class.spec.ts, src/session/models/fileSessionStore.class.ts, src/session/models/index.ts, src/session/models/redisSessionStore.class.ts
https://tools.hmcts.net/jira/browse/EUI-2057
Also fixed issue with cached authenticate method of wrapper
```
[ ] Yes
[ ] No
```
=> fix(xuinode): fixed dynamic import issue when compiling with webpack

.github/stale.yml
=> ci(bot): add stale bot config

.github/stale.yml, src/auth/oidc/models/openid.class.spec.ts, src/auth/oidc/models/openid.class.ts
=> ci(bot): Stalebot

package.json, src/auth/models/strategy.class.ts, src/auth/oidc/models/openid.class.ts, src/common/models/xuiNode.class.ts, tsconfig.json
Part of https://tools.hmcts.net/jira/browse/EUI-2057
```
[ ] Yes
[x] No
```
=> feat(auth): added bearer tokens and roles onto request headers

src/auth/models/strategy.class.ts, src/auth/oidc/models/OpenIDMetadata.interface.ts, src/auth/oidc/models/openid.class.spec.ts, src/auth/oidc/models/openid.class.ts
=> feat(callback url): middleware for dynamic callback

src/auth/oidc/models/openid.class.spec.ts
=> test(xuiNode): unit test keepAliveHandler

src/auth/models/strategy.class.ts, src/auth/oidc/models/openid.class.spec.ts, src/auth/oidc/models/openid.class.ts, src/index.ts
=> fix(tidy up): auth event success callback

release.config.js
=> ci(pipeline): test pre-release

yarn.lock
=> build(dependencies): update dependencies for CVE scanning

src/auth/models/strategy.class.ts
csrf cookie was only being set on login but validated on every request, hence open routes would fail.
```
[ ] Yes
[x] No
```
=> fix(csrf): cookie only set on login

package.json, yarn.lock
upgraded axios in order to overcome audit
```
[ ] Yes
[X] No
```
=> chore(package.json): upgrade axios

README.md
=> fix(test workflow): test bug fix workflow

src/auth/models/strategy.class.ts, src/auth/oidc/models/openid.class.spec.ts
https://tools.hmcts.net/jira/browse/EUI-3547
```
[ ] Yes
[X] No
```
=> fix(strategy.class.ts): routeCredentialToken expiry fix

src/auth/models/strategy.class.ts
=> style(strategy.class.ts): adding some logging

src/auth/models/strategy.class.ts
=> refactor(strategy.class.ts): adding log instead of info

src/auth/models/strategy.class.ts
=> fix(strategy.class.ts): add extra logging

package.json, src/auth/models/strategy.class.ts, src/auth/oidc/models/openid.class.spec.ts, src/common/models/xuiNode.class.ts
https://tools.hmcts.net/jira/browse/EUI-4261
Fix the Redirecting on node side.
```
[ ] Yes
[X] No
```
=> fix(strategy.class.ts): remove node redirect

README.md, src/auth/models/strategy.class.ts
https://tools.hmcts.net/jira/browse/EUI-4584
Bubbled up failed auth to the consuming project to handle (or ignore)
```
[ ] Yes
[x] No
```
=> fix: made sure that state failures are emitted to the consuming app

package.json
=> ci: bump version

docs/test.md
fix 123
```
[ ] Yes
[ ] No
```
=> fix: workflow test

docs/test.md
=> fix(workflow): workflow test

src/auth/models/strategy.class.ts
https://tools.hmcts.net/jira/browse/EUI-4584
Added more general error emitting to capture more
```
[ ] Yes
[x] No
```
=> fix: Feature/e UI 4584 invalid state pw

src/auth/models/strategy.class.ts
https://tools.hmcts.net/jira/browse/EUI-4584
Updated the error emit in the validation
```
[ ] Yes
[x] No
```
=> fix: Emit invalid state in all cases

src/session/models/redisSessionStore.class.ts
Add logging for redis Store
```
[ ] Yes
[ X ] No
```
=> refactor(redissessionstore.class.ts): logging of redisStore

package.json, src/auth/oidc/models/openid.class.ts
https://tools.hmcts.net/jira/browse/EUI-6845
Increased OIDC timeout
```
[ ] Yes
[x] No
```
=> fix(openid.class.ts): increased OIDC timeout

src/auth/models/strategy.class.ts
https://tools.hmcts.net/jira/browse/EUI-6853
Amalgamate multiple messages and emit once per process.
Change the false user clause message
```
[ ] Yes
[x] No
```
=> feat(strategy.ts): amalgamate multiple messages and emit once per process.

src/auth/models/strategy.class.ts
https://tools.hmcts.net/jira/browse/EUI-6853
Refactored my implementation
```
[ ] Yes
[x] No
```
=> fix(strategy.class.ts): refactored the failure emit

src/auth/models/strategy.class.ts, src/auth/oidc/models/openid.class.ts
https://tools.hmcts.net/jira/browse/EUI-6845
scratch PR at this point
```
[ ] Yes
[x] No
```
=> fix: added shorter timeout

src/auth/models/strategy.class.ts
https://tools.hmcts.net/jira/browse/EUI-6845
Resolved issue with log message being too large
```
[ ] Yes
[x] No
```
=> fix: fixed the app insight log

src/auth/models/strategy.class.ts, src/auth/oidc/models/openid.class.ts
https://tools.hmcts.net/jira/browse/EUI-7753
enhance error log
```
[ ] Yes
[x] No
```
=> fix: EUI 7753 enhance log

src/auth/models/strategy.class.ts, src/auth/oidc/models/openid.class.ts
eUI-7753: https://tools.hmcts.net/jira/browse/EUI-7753 
```
[ ] Yes
[x] No
```
=> fix: eUI-7753 Fixed the promises on login handler

src/auth/models/strategy.class.ts, src/auth/oidc/models/openid.class.ts
=> fix: e UI 7753

package.json
JIRA link (if applicable)
eUI-7753: https://tools.hmcts.net/jira/browse/EUI-7753
Change description
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
=> fix: reverted back to a previously working and compiling state

package.json, src/auth/models/strategy.class.ts, src/auth/oidc/models/openid.class.ts
=> fix: eUI 7753 reverted codeback

src/auth/models/strategy.class.ts
https://tools.hmcts.net/jira/browse/EUI-8549
Error Handling for Strategy name missing
```
[ ] Yes
[ x ] No
```
=> fix(strategy.class.ts): error handling

.github/workflows/prbuild.yml
Upgrade node-version from 12 to 14
```
[ ] Yes
[ ] No
```
=> fix(prpublish.yml): Node version upgrade

.github/renovate.json
Added renovate json file.
```
[ ] Yes
[ x] No
```
=> fix: added renovate json file

src/session/models/sessionMetadata.interface.ts
=> fix: maxAge made optional

README.md
=> chore: test change

README.md, package.json
=> feat: EXUI-382 session cookie

package.json, yarn.lock
=> fix: yarn lock

.github/workflows/prbuild.yml, package.json
https://tools.hmcts.net/jira/browse/EXUI-2531
adding yarn install
=> fix: Ex UI 2531 adding yarn install

package.json, src/auth/models/strategy.class.ts
https://tools.hmcts.net/jira/browse/EXUI-986
Add sameSite setting 'none' to XSRF cookie for Fortify issue
Verified does not affect MO (Will need to check no issues for MC or AO)
=> fix: Add samesite setting for XSRF

package.json, src/auth/models/strategy.class.ts
https://tools.hmcts.net/jira/browse/EXUI-2914
expired session issue
=> fix: #Exui-2914-expired session issue

package.json, src/auth/models/strategy.class.ts
See [EXUI-2541](https://tools.hmcts.net/jira/browse/EXUI-2541)
Same site
=> EXUI-2541 - New branch pre passport

package.json, src/auth/models/authOptions.interface.ts, src/auth/models/strategy.class.ts
https://tools.hmcts.net/jira/browse/EXUI-3465
sso logout issue
=> fix: exui-3465 sso sign out
